// Code generated by MockGen. DO NOT EDIT.
// Source: domain/addition.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAdditional is a mock of Additional interface.
type MockAdditional struct {
	ctrl     *gomock.Controller
	recorder *MockAdditionalMockRecorder
}

// MockAdditionalMockRecorder is the mock recorder for MockAdditional.
type MockAdditionalMockRecorder struct {
	mock *MockAdditional
}

// NewMockAdditional creates a new mock instance.
func NewMockAdditional(ctrl *gomock.Controller) *MockAdditional {
	mock := &MockAdditional{ctrl: ctrl}
	mock.recorder = &MockAdditionalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdditional) EXPECT() *MockAdditionalMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockAdditional) Add(a, b int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", a, b)
	ret0, _ := ret[0].(int)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockAdditionalMockRecorder) Add(a, b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockAdditional)(nil).Add), a, b)
}
